"use client";
import Link from "next/link";
import { useProducts } from "./use-products";
import { productInsights, analyzeProduct } from "./product-calculations";
import { formatMoney, formatQuantity, currencies } from "./product-model";
import { ActualComparison } from "./purchase-library";
import Skeleton from "../components/skeleton";
export default function ProductInsights() {
  const { records, loading, error } = useProducts();
  if (loading) return <Skeleton label="Loading product insights" />;
  if (error) return <p role="status" className="product-error">{error}</p>;
  const summary = productInsights(records), reviews = records.filter(r => r.status === "bought" && r.review);
  return <section className="product-insights" aria-labelledby="product-insights-heading"><h2 id="product-insights-heading">Learn from what you actually use.</h2>{!records.length ? <div className="product-empty"><h3>Start with one purchase in mind.</h3><p>Save a True Cost Receipt first. When you buy and review a product, your experience will appear here.</p><Link className="button-primary" href="/analyze">Analyze a product</Link></div> : <>
    <p className="insight-intro">{summary.reviewed === 0 ? "Your estimates are a starting point. Add a purchase review to see how they compare with experience." : summary.reviewed === 1 ? "One review is a useful observation, not a pattern. Start with the experience below." : `${summary.reviewed} purchase reviews to learn from. These describe your experience, not product quality for everyone.`}</p>
    <div className="product-summary-grid"><article><span>Products considered</span><strong>{records.length}</strong><p>{summary.counts.considering + summary.counts.postponed} considering or postponed · {summary.counts.skipped} skipped</p></article><article><span>Marked bought</span><strong>{summary.counts.bought}</strong><p>Choices you recorded, not verified transactions</p></article><article><span>Purchase reviews</span><strong>{summary.reviewed}</strong><p>{summary.again} would buy again · {summary.notAgain} would not</p></article></div>
    <p className="product-local-note">Estimates and recorded costs stay separate. Analyzing or skipping a product is not proof of money saved.</p>
    <div className="product-insight-grid"><section className="product-insight-panel"><h3>What you consider</h3><dl className="product-metrics">{Object.entries(summary.categories).sort((a,b) => b[1]-a[1]).map(([category,count]) => <div key={category}><dt>{category}</dt><dd>{count} {count === 1 ? "product" : "products"}</dd></div>)}</dl><p>Average planned reconsideration interval: {summary.averagePlannedWait === null ? "No scheduled dates yet." : `${formatQuantity(summary.averagePlannedWait)} days across ${summary.scheduledCount} schedules. This is a plan, not measured waiting behavior.`}</p></section><section className="product-insight-panel"><h3>Satisfaction, from actual reviews</h3>{Object.keys(summary.satisfaction).length ? <dl className="product-metrics">{Object.entries(summary.satisfaction).map(([category,item]) => <div key={category}><dt>{category}</dt><dd>{formatQuantity(item.sum/item.count)}/5 · {item.count} {item.count === 1 ? "rating" : "ratings"}</dd></div>)}</dl> : <p>No ratings yet. Add one to a purchase review when you have enough experience to judge.</p>}<p>Personal ratings describe your experience, not universal product quality.</p></section></div>
    <details className="product-insight-panel insight-cost-details"><summary>Estimated ownership costs, by currency</summary><p>Estimates across different ownership periods. Unknown costs are excluded. This is not a spending history or a product ranking.</p>{currencies.map(currency => { const items = records.filter(r => r.analysis.currency === currency).map(r => ({ record:r, result:analyzeProduct(r.analysis) })).sort((a,b) => b.result.net-a.result.net).slice(0,3); return items.length ? <div key={currency}><h4>{currency}</h4><dl className="product-metrics">{items.map(({record,result}) => <div key={record.id}><dt><Link href={`/analyze?id=${encodeURIComponent(record.id)}`}>{record.analysis.name}</Link></dt><dd>{formatMoney(result.net,currency)} / {result.months} months{result.missing.length ? " · incomplete assumptions" : ""}</dd></div>)}</dl></div> : null; })}</details>
    <section className="product-insight-panel"><h3>Expected use and recorded experience</h3>{reviews.length ? reviews.map(record => <details className="insight-review" key={record.id}><summary>{record.analysis.name}</summary><ActualComparison record={record} /></details>) : <p>No purchase reviews yet. Record your actual use and costs to see them beside the original estimate.</p>}<Link className="text-link" href="/purchases">Review your purchases →</Link></section>
  </>}</section>;
}
