"use client";
import Link from "next/link";
import { useProducts } from "./use-products";
import { productInsights, analyzeProduct } from "./product-calculations";
import { formatMoney, formatQuantity, currencies } from "./product-model";
import { ActualComparison } from "./purchase-library";
import Skeleton from "../components/skeleton";
export default function ProductInsights() {
  const { records, loading, error } = useProducts();
  if (loading) return <Skeleton label="Loading product insights" />;
  const summary = productInsights(records), reviews = records.filter(r => r.status === "bought" && r.review);
  return <section className="product-insights" aria-labelledby="product-insights-heading"><h2 id="product-insights-heading">Possibilities and experience, kept separate.</h2>{error && <p role="status" className="product-error">{error}</p>}{!records.length && !error ? <div className="product-empty"><h3>More information starts with one product.</h3><p>No product analyses yet. There are no trends to infer. Your existing GoalLens and savings insights remain below.</p><Link className="button-primary" href="/analyze">Analyze a product</Link></div> : <>
    <div className="product-summary-grid"><article><span>Products analyzed</span><strong>{records.length}</strong><p>Hypothetical cost models, including products later bought</p></article><article><span>Under consideration</span><strong>{summary.counts.considering + summary.counts.postponed}</strong><p>{summary.counts.postponed} postponed · {summary.counts.analyzed} analyzed only</p></article><article><span>Marked bought</span><strong>{summary.counts.bought}</strong><p>{summary.counts.skipped} skipped · self-reported choices</p></article><article><span>Purchase reviews</span><strong>{summary.reviewed}</strong><p>{summary.again} would buy again · {summary.notAgain} would not</p></article></div>
    <p className="product-notice">Analyzing or skipping a product does not prove money saved. No hypothetical costs or independent goal delays are combined into a claimed benefit.</p>
    <div className="product-insight-grid"><section className="product-insight-panel"><h3>What you consider</h3><dl className="product-metrics">{Object.entries(summary.categories).sort((a,b) => b[1]-a[1]).map(([category,count]) => <div key={category}><dt>{category}</dt><dd>{count} {count === 1 ? "product" : "products"}</dd></div>)}</dl><p>Average planned reconsideration interval: {summary.averagePlannedWait === null ? "No scheduled dates yet." : `${formatQuantity(summary.averagePlannedWait)} days across ${summary.scheduledCount} schedules. This is a plan, not measured waiting behavior.`}</p></section><section className="product-insight-panel"><h3>Satisfaction, from actual reviews</h3>{Object.keys(summary.satisfaction).length ? <dl className="product-metrics">{Object.entries(summary.satisfaction).map(([category,item]) => <div key={category}><dt>{category}</dt><dd>{formatQuantity(item.sum/item.count)}/5 · {item.count} {item.count === 1 ? "rating" : "ratings"}</dd></div>)}</dl> : <p>Insufficient data: add satisfaction ratings to purchased-product reviews. No score is inferred from spending or skipping.</p>}<p>Personal ratings describe your experience, not universal product quality.</p></section></div>
    <section className="product-insight-panel"><h3>Highest modeled ownership costs, by currency</h3><p>Estimates across different ownership periods. Unknown costs are excluded. This is not a spending history or a product ranking.</p>{currencies.map(currency => { const items = records.filter(r => r.analysis.currency === currency).map(r => ({ record:r, result:analyzeProduct(r.analysis) })).sort((a,b) => b.result.net-a.result.net).slice(0,3); return items.length ? <div key={currency}><h4>{currency}</h4><dl className="product-metrics">{items.map(({record,result}) => <div key={record.id}><dt><Link href={`/analyze?id=${encodeURIComponent(record.id)}`}>{record.analysis.name}</Link></dt><dd>{formatMoney(result.net,currency)} / {result.months} months{result.missing.length ? " · incomplete assumptions" : ""}</dd></div>)}</dl></div> : null; })}</section>
    <section className="product-insight-panel"><h3>Expected use and recorded experience</h3>{reviews.length ? reviews.map(record => <div key={record.id}><h4>{record.analysis.name}</h4><ActualComparison record={record} /></div>) : <p>Insufficient data. Record actual use and costs in Purchases to compare them with the original prediction.</p>}<Link className="text-link" href="/purchases">Review your purchases →</Link></section>
  </>}</section>;
}
